### ISSUE TITLE
react: improve the JobItem and JobList components

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#10]
[JobItem](https://github.com/madina0801/JobTrackr/blob/main/src/components/JobItem.jsx) component should display the following information about the job application:
- company name
- job title
- date applied
- status (applied, pending, interviewing, offer, rejected - may be extended in the future)
- notes (any text up to 250 characters)

**Comment by 999Debi** [comment]
Your application only accepts company name,position ,Date applied .How status determined from that  if it is pending,rejected,selected or anything ? what should be in  description and notes ?
plesase clarify me first ,them allow me to do that for you 🙂

**Comment by 999Debi** [comment]
Please assign me

**Comment by madina0801** [comment]
I updated the description of the issue, so check it out~
You'd also need to improve the JobList that's the parent component ☺️
Feel free to reach out to me!

**Comment by 999Debi** [comment]
Anything you want to add to this project
