### ISSUE TITLE
react: JobItem component - add delete option

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#13]
Now it renders JobItem and save it locally in the local storage. Need to have the delete option:
- Use react-icons (already installed) to add "delete" icon to the JobItem component
- Should also delete JobItem from the localStorage

**Comment by Skipper-kenya** [comment]
I have enhanced the functionality. consider to merge my request.

**Comment by Skipper-kenya** [comment]
**check my latest pull request I have enhanced the requirements.**
