### ISSUE TITLE
react: render div depending on a certain coniditon

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#21]
We have All Jobs heading in [JobList component](https://github.com/madina0801/JobTrackr/blob/main/src/components/JobList.jsx)
The div that contains this heading needs to be shown only if there are saved jobs ("jobAplications') in the localStorage. When localStorage is empty, this heading shouldn't be seen. This div:
This div:
https://github.com/madina0801/JobTrackr/blob/8ce4afb4e5feed9985d00b7e2f923fd867050fb0/src/components/JobList.jsx#L8

**Comment by CalenCoop** [comment]
I'd love to give this a try!
