### ISSUE TITLE
style: center a line

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#25]
Center this line in [About](https://github.com/madina0801/JobTrackr/blob/main/src/components/About.jsx) component
https://github.com/madina0801/JobTrackr/blob/fd4eefb7d109df5e4dbfc501f12b434f82027957/src/components/About.jsx#L11

**Comment by bryokim** [comment]
I would like to work on this issue

**Comment by madina0801** [comment]
You got it :)
