### ISSUE TITLE
Upgrade README.md & CONTRIBUTING.md

### ISSUE THREAD

**Issue by NalimWeso** [madina0801/JobTrackr#26]
Hey hey!

I noticed there are quite basic MD files here. I could improve them a bit so they don't look so mundane. More colors would be useful, maybe some badges too. Definitely, I would polish the text, take care of punctuation and similar things.

Could I take care of that?

**Comment by madina0801** [comment]
Sure! They're written in haste so feel free to upgrade them. I'd appreciate it :)
