### ISSUE TITLE
Footer does not stick to the bottom

### ISSUE THREAD

**Issue by bryokim** [madina0801/JobTrackr#29]
To make the footer stick, I propose making the app to have a minimum height equal to the viewport height and the footer sticky with a top of the viewport height.

Using tailwind this can be achieved by adding the `min-h-dvh` class to app and  `sticky` with `top-[100vh]` to the footer.

**Comment by madina0801** [comment]
Could you please implement this and I'll take a look?~ Everything works as intended on my side 🤔

**Comment by bryokim** [comment]
Sure. Let me get on it.
