### ISSUE TITLE
react: create a JobItem React component

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#3]
Create a separate React component for JobItem that will be rendered in the JobList component [/JobList.jsx](https://github.com/madina0801/JobTrackr/blob/main/src/components/JobList.jsx)

**Comment by sanketyelave** [comment]
Hey,
Can you please assign this task to me.

**Comment by madina0801** [comment]
Hey, @sanketyelave ! I'm sorry this issue is already solved, maybe you could help me out with the Navbar component? Ask to assign you [here](https://github.com/madina0801/JobTrackr/issues/5) if you're interested! :)
