### ISSUE TITLE
style: make a mobile navbar prettier

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#34]
Now we have a [Navbar component](https://github.com/madina0801/JobTrackr/blob/main/src/components/layout/Navbar.jsx), mobile Navbar is in content variable: https://github.com/madina0801/JobTrackr/blob/e11d391ea6136cfa4cc60cb8e8506b9a09def38e/src/components/layout/Navbar.jsx#L22
It looks bad now, make following changes:
- [ ] light blurred (glass-like) background
- [ ] height needs to be for the full screen
- [ ] more space between links
- [ ] link text needs to be dark
- [ ] link font size needs to be bigger

**Comment by bryokim** [comment]
I'd love to give this a try

**Comment by madina0801** [comment]
Sure :)
