### ISSUE TITLE
react: update the navbar component

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#5]
Update the Navbar component, it's created but empty. It needs to include:

- [ ] Logo (can be found [here](https://github.com/madina0801/JobTrackr/blob/main/logo.svg))
- [ ] Title (JobTrackr)
- [ ] About - leads to the "/" for now
- [ ] GitHub - leads to the [this repo](https://github.com/madina0801/JobTrackr1)

**Comment by sanketyelave** [comment]
Yess I am interested , Assign me this one 🙂

**Comment by madina0801** [comment]
You got it :)
